projects/urls.py
from django.urls import path

from . import views

# Essa variável diz a qual app pertence a url dinâmica nos templates
# https://docs.djangoproject.com/en/5.1/intro/tutorial03/#namespacing-url-names
app_name = "projects"
# Essa lista deve conter as rotas para as funcoes definidas em projects/views.py
urlpatterns = [
    path("", views.ProjectListView.as_view(), name="index"),
    path("project/<int:pk>", views.ProjectDetailView.as_view(), name="project"),
    path("project/add", views.ProjectCreateView.as_view(), name="add_project"),
    path(
        "project/<int:pk>/edit", views.ProjectUpdateView.as_view(), name="edit_project"
    ),
    path(
        "project/<int:pk>/delete",
        views.ProjectDeleteView.as_view(),
        name="delete_project",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>",
        views.TaskDetailView.as_view(),
        name="task",
    ),
    path(
        "project/<int:project_id>/task/add",
        views.TaskCreateView.as_view(),
        name="add_task",
    ),
    path("task/add", views.TaskCreateView.as_view(), name="add_task_global"),
    path(
        "project/<int:project_id>/task/<int:task_id>/edit",
        views.TaskUpdateView.as_view(),
        name="edit_task",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>/update-status/",
        views.TaskStatusUpdateView.as_view(),
        name="update_task_status",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>/delete",
        views.TaskDeleteView.as_view(),
        name="delete_task",
    ),
]

setup/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# Nessa lista devem ser colocadas as urls criadas no projects/urls.py
urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("projects.urls")),
        path("users/", include("users.urls")),
    ]
    + debug_toolbar_urls()
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

tprojects/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

projects/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.widgets import Textarea, TextInput, Select, SelectMultiple

from projects.models import Project, Task


# https://docs.djangoproject.com/en/5.1/ref/forms/fields/#iterating-relationship-choices
class UserSelectMultiple(SelectMultiple):
    def create_option(
        self, name, value, label, selected, index, subindex=None, attrs=None
    ):
        option = super().create_option(
            name, value, label, selected, index, subindex=subindex, attrs=attrs
        )
        # Verifica se o valor não é None e obtém o ID correto
        if value is not None and hasattr(value, "value"):
            user_id = value.value  # Captura o ID corretamente
        else:
            user_id = value  # Caso seja um número normal
        user = User.objects.get(pk=user_id)  # Obtém o usuário
        option["attrs"][
            "data-avatar"
        ] = user.profile.avatar.url  # Sempre terá um avatar
        return option


# https://docs.djangoproject.com/en/5.1/topics/forms/modelforms/#overriding-the-default-fields
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]
        labels = {
            "name": "Nome do projeto",
            "description": "Descrição do projeto",
        }
        widgets = {
            "name": TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Digite o nome do projeto",
                }
            ),
            "description": Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Insira a descrição do projeto",
                }
            ),
        }


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "status",
            "related_project",
            "responsible",
            "collaborators",
        ]
        labels = {
            "name": "Nome da Tarefa",
            "description": "Descrição da Tarefa",
            "related_project": "Projeto Relacionado",
            "status": "Status da Tarefa",
            "responsible": "Responsável pela tarefa",
            "collaborators": "Colaboradores da tarefa",
        }
        widgets = {
            "name": TextInput(attrs={"class": "form-control"}),
            "description": Textarea(attrs={"class": "form-control"}),
            "status": Select(attrs={"class": "form-select"}),
            "related_project": Select(attrs={"class": "form-select"}),
            "responsible": Select(attrs={"class": "form-select"}),
            "collaborators": UserSelectMultiple(
                attrs={
                    "class": "js-example-basic-multiple",
                    "name": "collaborators[]",
                    "multiple": "multiple",
                }
            ),
        }

projects/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import ProjectForm, TaskForm
from .models import Project, Task


class ProjectCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/add_project.html"
    model = Project
    template_name = "projects/add_project.html"
    permission_required = "projects.add_project"
    # O atributo form_class serve apenas para usar as labels e widgets definidos no forms.py.
    # Caso for preferível usar o nome padrão dos campos (definido no models.py), basta comentar a linha abaixo.
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Projeto criado com sucesso!")
        return response


class ProjectListView(LoginRequiredMixin, ListView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Project
    template_name = "projects/index.html"
    # Numa view genérica, o contexto é criado automaticamente com base no modelo usado e no tipo de genérico usado.
    # Nesse caso, o nome do objeto de contexto é "project_list"
    #                                             ^^^^^^^ ^^^^
    #                                      nome do modelo|nome do tipo de view genérica
    # Caso queira mudar o nome do objeto de contexto, basta mudar o parâmetro context_object_name
    # https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/#making-friendly-template-contexts


class ProjectDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    # A classe genérica DetailView espera que uma chave primária seja passada como um parâmetro
    # na url chamado "pk" por padrão. Isso é usado para determinar qual objeto (nesse caso, um Project) deve
    # ser recuperado do banco de dados.
    login_url = "/users/login/"
    redirect_field_name = "projects/project.html"
    model = Project
    template_name = "projects/project.html"
    context_object_name = "current_project"
    permission_required = "projects.view_project"

    def get_context_data(self, **kwargs):
        # O override do metodo "get_context_data" permite que seja criado um objeto de contexto personalizado, baseado
        # na chave primária passada na url. Isso serve para passar como contexto adicional objetos relacionados ao pk
        # ou algo que não dependa dessa chave primária
        context = super().get_context_data(
            **kwargs
        )  # Linha obrigatória para criar o objeto contexto.
        # Adicionando tarefas relacionadas ao contexto
        context["project_tasks"] = Task.objects.filter(
            related_project=self.object
        ).order_by("-status")
        return context

    # https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/#adding-extra-context


class ProjectUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/edit_project.html"
    model = Project
    template_name = "projects/edit_project.html"
    context_object_name = "current_project"
    permission_required = "projects.change_project"
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Projeto atualizado com sucesso!")
        return response


class ProjectDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Project
    template_name = "projects/delete_project.html"
    context_object_name = "current_project"
    permission_required = "projects.delete_project"
    success_url = reverse_lazy("projects:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Projeto excluído com sucesso!")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related_tasks"] = Task.objects.filter(related_project=self.object)
        return context


class TaskCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/add_task.html"
    model = Task
    form_class = TaskForm
    template_name = "projects/add_task.html"
    permission_required = "projects.add_task"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if "project_id" in self.kwargs:
            # Remove o campo related_project do formulário quando há project_id na URL
            del form.fields["related_project"]
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        if project_id:
            context["current_project"] = get_object_or_404(Project, id=project_id)

        return context

    def form_valid(self, form):
        project_id = self.kwargs.get("project_id")

        if project_id:
            # Se um project_id foi passado na URL, associa automaticamente a task a esse projeto
            form.instance.related_project = get_object_or_404(Project, id=project_id)
        elif not form.instance.related_project:
            # Se a task for adicionada sem project_id, o usuário deve escolher um projeto manualmente
            messages.error(self.request, "Selecione um projeto para a tarefa.")
            return self.form_invalid(form)

        form.instance.created_by = self.request.user
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Task criada com sucesso!")
        return response

    def get_success_url(self):
        return reverse(
            "projects:task", args=[self.object.related_project.id, self.object.id]
        )


class TaskDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "/users/login/"
    redirect_field_name = "projects/task.html"
    model = Task
    template_name = "projects/task.html"
    context_object_name = "current_task"
    permission_required = "projects.view_task"

    def get_object(self, queryset=None):
        # Override get_object to retrieve the specific Task object based on task_id and project_id.
        project_id = self.kwargs.get("project_id")
        task_id = self.kwargs.get("task_id")

        # Fetch the specific task that belongs to the given project
        return get_object_or_404(Task, pk=task_id, related_project_id=project_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        # Get the project using the project_id
        context["current_project"] = get_object_or_404(Project, pk=project_id)
        return context

    def get_success_url(self):
        # Redireciona para a página do projeto relacionado após a criação da tarefa.
        return reverse("projects:project", args=[self.object.related_project.id])


class TaskUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/edit_task.html"
    model = Task
    template_name = "projects/edit_task.html"
    context_object_name = "current_task"
    permission_required = "projects.change_task"
    form_class = TaskForm

    def form_valid(self, form):
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Tarefa atualizada com sucesso!")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        # Get the project using the project_id
        context["current_project"] = get_object_or_404(Project, pk=project_id)
        return context

    def get_object(self, queryset=None):
        # Override get_object to retrieve the specific Task object based on task_id and project_id.
        project_id = self.kwargs.get("project_id")
        task_id = self.kwargs.get("task_id")

        # Fetch the specific task that belongs to the given project
        return get_object_or_404(Task, pk=task_id, related_project_id=project_id)


class TaskStatusUpdateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "projects.change_task"

    def post(self, request, project_id, task_id):
        task = get_object_or_404(Task, pk=task_id, related_project_id=project_id)
        new_status = request.POST.get("status")
        valid_statuses = dict(Task.STATUS_CHOICES).keys()

        if new_status in valid_statuses:
            task.status = new_status
            task.last_edited_by = request.user
            task.save()
            messages.success(request, "Status atualizado com sucesso!")
        else:
            messages.error(request, "Status inválido!")

        return redirect("projects:task", project_id=project_id, task_id=task_id)


class TaskDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Task
    template_name = "projects/delete_task.html"
    context_object_name = "current_task"

projects/templates/projects/partials/base.html
<!doctype html>
<html lang="en" class="min-vh-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Project Manager{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <style>
        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        main {
            flex: 1 0 auto;
        }

        .navbar-brand {
            font-weight: 600;
        }

        .alert {
            margin-bottom: 0;
            border: 0;
            border-radius: 0;
        }

        .avatar-small {
            width: 25px;
            height: 25px;
            object-fit: cover;
        }


    </style>
    {% block extra_css %}{% endblock %}
</head>
<body>
<!-- Alert Messages -->
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <div class="container">
                <div class="d-flex align-items-center">
                    {% if message.tags == 'success' %}
                        <i class="fas fa-check-circle me-2"></i>
                    {% elif message.tags == 'error' %}
                        <i class="fas fa-exclamation-circle me-2"></i>
                    {% elif message.tags == 'warning' %}
                        <i class="fas fa-exclamation-triangle me-2"></i>
                    {% elif message.tags == 'info' %}
                        <i class="fas fa-info-circle me-2"></i>
                    {% endif %}
                    {{ message }}
                    <button type="button" class="btn-close ms-auto" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'projects:index' %}">
            <i class="fas fa-tasks text-primary me-2"></i>
            Gerenciador de Projetos
        </a>

        {% if user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarContent">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:index' %}">
                            <i class="fas fa-home me-1"></i> Início
                        </a>
                    </li>
                </ul>

                <div class="d-flex align-items-center gap-3">
                    {% if greeting %}
                        <div class="text-muted d-flex align-items-center">
                            <img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}'s avatar"
                                 class="rounded-circle me-2 avatar-small"
                                 style="width: 25px; height: 25px; object-fit: cover;">
                            {{ greeting }}, {{ user.username }}
                        </div>
                    {% endif %}

                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-outline-primary">
                            <i class="fas fa-sign-out-alt me-1"></i>
                            Fazer Logout
                        </button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
</nav>

<!-- Main Content -->
<main class="py-4">
    {% block content %}
        <!-- Specific page content goes here -->
    {% endblock %}
</main>

<!-- Footer -->
<footer class="py-4 bg-light mt-auto">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 text-center">
                <p class="text-muted mb-0">
                    <small>
                        &copy; {{ current_datetime.year }} Gerenciador de Projetos.
                        Todos os direitos reservados.
                    </small>
                </p>
            </div>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    function formatState(state) {
        if (!state.id) {
            return state.text;
        }

        // Obtém a URL do avatar da opção selecionada
        var avatarUrl = $(state.element).data("avatar");

        // Retorna o HTML formatado com a imagem correta para cada usuário
        return $('<span><img src="' + avatarUrl + '" class="avatar-small"/> ' + state.text + '</span>');
    }


    $(document).ready(function () {
        $(".js-example-basic-multiple").select2({
            templateResult: formatState,  // Formata as opções com imagem
            templateSelection: formatState  // Formata a opção selecionada
        });
    });
</script>
{% block extra_js %}{% endblock %}
</body>
</html>