projects/urls.py
from django.urls import path

from . import views

# Essa variável diz a qual app pertence a url dinâmica nos templates
# https://docs.djangoproject.com/en/5.1/intro/tutorial03/#namespacing-url-names
app_name = "projects"
# Essa lista deve conter as rotas para as funcoes definidas em projects/views.py
urlpatterns = [
    path("", views.ProjectListView.as_view(), name="index"),
    path("project/<int:pk>", views.ProjectDetailView.as_view(), name="project"),
    path("project/add", views.ProjectCreateView.as_view(), name="add_project"),
    path(
        "project/<int:pk>/edit", views.ProjectUpdateView.as_view(), name="edit_project"
    ),
    path(
        "project/<int:pk>/delete",
        views.ProjectDeleteView.as_view(),
        name="delete_project",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>",
        views.TaskDetailView.as_view(),
        name="task",
    ),
    path(
        "project/<int:project_id>/task/add",
        views.TaskCreateView.as_view(),
        name="add_task",
    ),
    path("task/add", views.TaskCreateView.as_view(), name="add_task_global"),
    path(
        "project/<int:project_id>/task/<int:task_id>/edit",
        views.TaskUpdateView.as_view(),
        name="edit_task",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>/update-status/",
        views.TaskStatusUpdateView.as_view(),
        name="update_task_status",
    ),
    path(
        "project/<int:project_id>/task/<int:task_id>/delete",
        views.TaskDeleteView.as_view(),
        name="delete_task",
    ),
]

setup/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# Nessa lista devem ser colocadas as urls criadas no projects/urls.py
urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("projects.urls")),
        path("users/", include("users.urls")),
    ]
    + debug_toolbar_urls()
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

tprojects/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

projects/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    # Quando duas ou mais propriedades de um modelo se referem a um mesmo outro modelo, o kwarg
    # related_name deve ser passado.
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name="projects_created"
    )
    last_edited_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name="last_edited_projects"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # Quando um formulário for preenchido para criar um objeto desse modelo, retorna a página
        # de detalhes desse projeto
        return reverse("projects:project", kwargs={"pk": self.pk})


class Task(models.Model):
    STATUS_CHOICES = [
        ("TODO", "A Fazer"),
        ("IN PROGRESS", "Fazendo"),
        ("PAUSED", "Pausado"),
        ("DONE", "Concluído"),
        ("CANCELED", "Cancelado"),
    ]

    name = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default="TODO")
    created_at = models.DateTimeField(auto_now_add=True)
    related_project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name="tasks_created"
    )
    last_edited_by = models.ForeignKey(
        User, on_delete=models.DO_NOTHING, related_name="last_edited_tasks"
    )
    responsible = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        related_name="assigned_tasks",
        blank=True,
        null=True,
    )
    collaborators = models.ManyToManyField(
        User,
        related_name="tasks_collaborators",
        blank=True,
        help_text="Opcional. Adicione pessoas relevantes para acompanhar a tarefa.",
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # Quando um formulário for preenchido para criar um objeto desse modelo, retorna a página
        # de detalhes desse projeto
        return reverse(
            "projects:task",
            kwargs={"project_id": self.related_project_id, "task_id": self.id},
        )

projects/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.widgets import Textarea, TextInput, Select, SelectMultiple

from projects.models import Project, Task


# https://docs.djangoproject.com/en/5.1/ref/forms/fields/#iterating-relationship-choices
class UserSelectMultiple(SelectMultiple):
    def create_option(
        self, name, value, label, selected, index, subindex=None, attrs=None
    ):
        option = super().create_option(
            name, value, label, selected, index, subindex=subindex, attrs=attrs
        )
        # Verifica se o valor não é None e obtém o ID correto
        if value is not None and hasattr(value, "value"):
            user_id = value.value  # Captura o ID corretamente
        else:
            user_id = value  # Caso seja um número normal
        user = User.objects.get(pk=user_id)  # Obtém o usuário
        option["attrs"][
            "data-avatar"
        ] = user.profile.avatar.url  # Sempre terá um avatar
        return option


# https://docs.djangoproject.com/en/5.1/topics/forms/modelforms/#overriding-the-default-fields
class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]
        labels = {
            "name": "Nome do projeto",
            "description": "Descrição do projeto",
        }
        widgets = {
            "name": TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Digite o nome do projeto",
                }
            ),
            "description": Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Insira a descrição do projeto",
                }
            ),
        }


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "description",
            "status",
            "related_project",
            "responsible",
            "collaborators",
        ]
        labels = {
            "name": "Nome da Tarefa",
            "description": "Descrição da Tarefa",
            "related_project": "Projeto Relacionado",
            "status": "Status da Tarefa",
            "responsible": "Responsável pela tarefa",
            "collaborators": "Colaboradores da tarefa",
        }
        widgets = {
            "name": TextInput(attrs={"class": "form-control"}),
            "description": Textarea(attrs={"class": "form-control"}),
            "status": Select(attrs={"class": "form-select"}),
            "related_project": Select(attrs={"class": "form-select"}),
            "responsible": Select(attrs={"class": "form-select"}),
            "collaborators": UserSelectMultiple(
                attrs={
                    "class": "js-example-basic-multiple",
                    "name": "collaborators[]",
                    "multiple": "multiple",
                }
            ),
        }

projects/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, reverse, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import ProjectForm, TaskForm
from .models import Project, Task


class ProjectCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/add_project.html"
    model = Project
    template_name = "projects/add_project.html"
    permission_required = "projects.add_project"
    # O atributo form_class serve apenas para usar as labels e widgets definidos no forms.py.
    # Caso for preferível usar o nome padrão dos campos (definido no models.py), basta comentar a linha abaixo.
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Projeto criado com sucesso!")
        return response


class ProjectListView(LoginRequiredMixin, ListView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Project
    template_name = "projects/index.html"
    # Numa view genérica, o contexto é criado automaticamente com base no modelo usado e no tipo de genérico usado.
    # Nesse caso, o nome do objeto de contexto é "project_list"
    #                                             ^^^^^^^ ^^^^
    #                                      nome do modelo|nome do tipo de view genérica
    # Caso queira mudar o nome do objeto de contexto, basta mudar o parâmetro context_object_name
    # https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/#making-friendly-template-contexts


class ProjectDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    # A classe genérica DetailView espera que uma chave primária seja passada como um parâmetro
    # na url chamado "pk" por padrão. Isso é usado para determinar qual objeto (nesse caso, um Project) deve
    # ser recuperado do banco de dados.
    login_url = "/users/login/"
    redirect_field_name = "projects/project.html"
    model = Project
    template_name = "projects/project.html"
    context_object_name = "current_project"
    permission_required = "projects.view_project"

    def get_context_data(self, **kwargs):
        # O override do metodo "get_context_data" permite que seja criado um objeto de contexto personalizado, baseado
        # na chave primária passada na url. Isso serve para passar como contexto adicional objetos relacionados ao pk
        # ou algo que não dependa dessa chave primária
        context = super().get_context_data(
            **kwargs
        )  # Linha obrigatória para criar o objeto contexto.
        # Adicionando tarefas relacionadas ao contexto
        context["project_tasks"] = Task.objects.filter(
            related_project=self.object
        ).order_by("-status")
        return context

    # https://docs.djangoproject.com/en/5.1/topics/class-based-views/generic-display/#adding-extra-context


class ProjectUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/edit_project.html"
    model = Project
    template_name = "projects/edit_project.html"
    context_object_name = "current_project"
    permission_required = "projects.change_project"
    form_class = ProjectForm

    def form_valid(self, form):
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Projeto atualizado com sucesso!")
        return response


class ProjectDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Project
    template_name = "projects/delete_project.html"
    context_object_name = "current_project"
    permission_required = "projects.delete_project"
    success_url = reverse_lazy("projects:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, "Projeto excluído com sucesso!")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["related_tasks"] = Task.objects.filter(related_project=self.object)
        return context


class TaskCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/add_task.html"
    model = Task
    form_class = TaskForm
    template_name = "projects/add_task.html"
    permission_required = "projects.add_task"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        if "project_id" in self.kwargs:
            # Remove o campo related_project do formulário quando há project_id na URL
            del form.fields["related_project"]
        return form

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        if project_id:
            context["current_project"] = get_object_or_404(Project, id=project_id)

        return context

    def form_valid(self, form):
        project_id = self.kwargs.get("project_id")

        if project_id:
            # Se um project_id foi passado na URL, associa automaticamente a task a esse projeto
            form.instance.related_project = get_object_or_404(Project, id=project_id)
        elif not form.instance.related_project:
            # Se a task for adicionada sem project_id, o usuário deve escolher um projeto manualmente
            messages.error(self.request, "Selecione um projeto para a tarefa.")
            return self.form_invalid(form)

        form.instance.created_by = self.request.user
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Task criada com sucesso!")
        return response

    def get_success_url(self):
        return reverse(
            "projects:task", args=[self.object.related_project.id, self.object.id]
        )


class TaskDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = "/users/login/"
    redirect_field_name = "projects/task.html"
    model = Task
    template_name = "projects/task.html"
    context_object_name = "current_task"
    permission_required = "projects.view_task"

    def get_object(self, queryset=None):
        # Override get_object to retrieve the specific Task object based on task_id and project_id.
        project_id = self.kwargs.get("project_id")
        task_id = self.kwargs.get("task_id")

        # Fetch the specific task that belongs to the given project
        return get_object_or_404(Task, pk=task_id, related_project_id=project_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        # Get the project using the project_id
        context["current_project"] = get_object_or_404(Project, pk=project_id)
        return context

    def get_success_url(self):
        # Redireciona para a página do projeto relacionado após a criação da tarefa.
        return reverse("projects:project", args=[self.object.related_project.id])


class TaskUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = "/users/login/"
    redirect_field_name = "projects/edit_task.html"
    model = Task
    template_name = "projects/edit_task.html"
    context_object_name = "current_task"
    permission_required = "projects.change_task"
    form_class = TaskForm

    def form_valid(self, form):
        form.instance.last_edited_by = self.request.user
        response = super().form_valid(form)
        messages.success(self.request, "Tarefa atualizada com sucesso!")
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project_id = self.kwargs.get("project_id")

        # Get the project using the project_id
        context["current_project"] = get_object_or_404(Project, pk=project_id)
        return context

    def get_object(self, queryset=None):
        # Override get_object to retrieve the specific Task object based on task_id and project_id.
        project_id = self.kwargs.get("project_id")
        task_id = self.kwargs.get("task_id")

        # Fetch the specific task that belongs to the given project
        return get_object_or_404(Task, pk=task_id, related_project_id=project_id)


class TaskStatusUpdateView(LoginRequiredMixin, PermissionRequiredMixin, View):
    permission_required = "projects.change_task"

    def post(self, request, project_id, task_id):
        task = get_object_or_404(Task, pk=task_id, related_project_id=project_id)
        new_status = request.POST.get("status")
        valid_statuses = dict(Task.STATUS_CHOICES).keys()

        if new_status in valid_statuses:
            task.status = new_status
            task.last_edited_by = request.user
            task.save()
            messages.success(request, "Status atualizado com sucesso!")
        else:
            messages.error(request, "Status inválido!")

        return redirect("projects:task", project_id=project_id, task_id=task_id)


class TaskDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = "/users/login/"
    redirect_field_name = "projects/index.html"
    model = Task
    template_name = "projects/delete_task.html"
    context_object_name = "current_task"

projects/templates/projects/add_task.html
{% extends "projects/partials/base.html" %}
{% load form_filters %}

{% block title %}Adicionar Task{% endblock %}

{% block content %}
    <div class="container py-4">
        <div class="row justify-content-center">
            <div class="col-12 col-md-8 col-lg-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h1 class="card-title h3 mb-4">Adicionar Nova Task</h1>

                        <form method="post" action="
                                {% if current_project %}{% url 'projects:add_task' current_project.id %}{% else %}{% url 'projects:add_task_global' %}{% endif %}">
                            {% csrf_token %}

                            {% for field in form %}
                                <div class="mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <div class="form-text">{{ field.help_text }}</div>
                                    {% endif %}
                                </div>
                            {% endfor %}

                            <div class="d-flex gap-2 justify-content-end mt-4">
                                <a href="
                                        {% if current_project %}{% url 'projects:project' current_project.id %}{% else %}{% url 'projects:index' %}{% endif %}"
                                   class="btn btn-outline-secondary">
                                    <i class="fas fa-times me-2"></i>Cancelar
                                </a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fas fa-plus-circle me-2"></i>Criar Task
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

projects/templates/projects/index.html
{% extends "projects/partials/base.html" %}

{% block title %}Gerenciador de Projetos{% endblock %}

{% block content %}
    <div class="container py-4">
        <!-- Action buttons -->
        <div class="d-flex gap-3 mb-4">
            <a href="{% url 'projects:add_project' %}" class="btn btn-primary">
                <i class="fas fa-plus-circle me-2"></i>Novo Projeto
            </a>
            <a href="{% url 'projects:add_task_global' %}" class="btn btn-outline-secondary">
                <i class="fas fa-tasks me-2"></i>Nova Task
            </a>
        </div>

        {% if project_list %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
                {% for projeto in project_list %}
                    <div class="col">
                        <div class="card h-100 shadow-sm hover-shadow">
                            <div class="card-body">
                                <div class="d-flex justify-content-between align-items-start mb-2">
                                    <h2 class="card-title h4 mb-0" style="max-width: 80%; word-wrap: break-word;">
                                        {{ projeto.name }}
                                    </h2>
                                    <span class="badge bg-primary rounded-pill ms-2 flex-shrink-0">
                                    {{ projeto.task_set.count }} tasks
                                </span>
                                </div>

                                <p class="card-text text-muted mb-3 text-truncate"
                                   style="max-height: 4.5rem; overflow: hidden; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical;">
                                    {{ projeto.description|truncatewords:30 }}
                                </p>

                                <a href="{% url 'projects:project' projeto.id %}"
                                   class="btn btn-outline-primary btn-sm stretched-link">
                                    Ver detalhes <i class="fas fa-arrow-right ms-1"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="text-center py-5">
                <div class="mb-4">
                    <i class="fas fa-folder-open text-muted" style="font-size: 4rem;"></i>
                </div>
                <h3 class="h4 mb-3">Nenhum projeto encontrado</h3>
                <p class="text-muted">Comece criando seu primeiro projeto!</p>
                <a href="{% url 'projects:add_project' %}" class="btn btn-primary mt-2">
                    Criar Projeto
                </a>
            </div>
        {% endif %}
    </div>
    {% block extra_css %}
    <style>
        /* Custom styles for cards */
        .card {
            transition: transform 0.2s ease-in-out, box-shadow 0.2s ease-in-out;
        }

        .card:hover {
            transform: translateY(-5px);
            box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15) !important;
        }

        /* Ensure the badge stays on one line */
        .badge {
            white-space: nowrap;
        }

        /* Custom truncation for long titles */
        .card-title {
            overflow-wrap: break-word;
            hyphens: auto;
            line-height: 1.3;
            min-height: 1.3em;
        }
    </style>
    {% endblock %}
{% endblock %}

projects/templates/projects/project.html
{% extends "projects/partials/base.html" %}
{% load project_filters %}

{% block title %}{{ current_project.name }}{% endblock %}

{% block content %}
    <div class="container py-4">
        <!-- Project Header -->
        <div class="row mb-4">
            <div class="col">
                <div class="d-flex justify-content-between align-items-start">
                    <h1 class="display-5 mb-0">{{ current_project.name }}</h1>
                    <div class="btn-group">
                        <a href="{% url 'projects:edit_project' current_project.id %}" class="btn btn-outline-primary">
                            <i class="fas fa-edit me-2"></i>Editar
                        </a>
                        <a href="{% url 'projects:delete_project' current_project.id %}" class="btn btn-outline-danger">
                            <i class="fas fa-trash-alt me-2"></i>Excluir
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Project Description -->
        <div class="row mb-4">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h2 class="h5 card-title text-muted mb-3">Descrição</h2>
                        <p class="card-text">{{ current_project.description }}</p>

                        <hr class="my-3">

                        <div class="d-flex justify-content-between text-muted small">
                        <span>
                            <i class="fas fa-user me-1"></i> Criado por {{ current_project.created_by.username }}
                        </span>
                            <span>
                            <i class="fas fa-edit me-1"></i> Última edição por {{ current_project.last_edited_by.username }}
                        </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Tasks Section -->
        <!-- Tasks Section -->
        <!-- Tasks Section -->
        <div class="row">
            <div class="col">
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <h2 class="h3 mb-0">Tarefas</h2>
                    <a href="{% url 'projects:add_task' current_project.id %}" class="btn btn-primary">
                        <i class="fas fa-plus-circle me-2"></i>Nova Tarefa
                    </a>
                </div>

                {% if project_tasks %}
                    <div class="table-responsive">
                        {% regroup project_tasks by get_status_display as status_list %}
                        {% for status in status_list %}
                            <div class="d-flex align-items-center gap-2 mt-4 mb-3">
                                <h4 class="mb-0">
                                    <span class="badge bg-{{ status.list.0.status|status_to_bootstrap_class }} p-2">
                                        {% if status.grouper == 'A Fazer' %}
                                            <i class="fas fa-clipboard-list me-2"></i>
                                        {% elif status.grouper == 'Fazendo' %}
                                            <i class="fas fa-spinner me-2"></i>
                                        {% elif status.grouper == 'Pausado' %}
                                            <i class="fas fa-pause me-2"></i>
                                        {% elif status.grouper == 'Concluído' %}
                                            <i class="fas fa-check me-2"></i>
                                        {% elif status.grouper == 'Cancelado' %}
                                            <i class="fas fa-times me-2"></i>
                                        {% endif %}
                                        {{ status.grouper }}
                                    </span>
                                </h4>
                                <span class="text-muted small">({{ status.list|length }}
                                    {% if status.list|length == 1 %}tarefa{% else %}tarefas{% endif %})</span>
                            </div>
                            <table class="table table-hover align-middle">
                                <thead>
                                <tr>
                                    <th style="width: 25%">Nome</th>
                                    <th style="width: 45%">Descrição</th>
                                    <th style="width: 15%">Data de Criação</th>
                                    <th style="width: 15%" class="text-end">Ações</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for task in status.list %}
                                    <tr>
                                        <td>
                                                <a href="{% url 'projects:task' current_project.id task.id %}"
                                                   class="text-decoration-none">
                                                    {{ task.name }}
                                                </a>
                                        </td>
                                        <td class="text-muted">{{ task.description|truncatewords:20 }}</td>
                                        <td>{{ task.created_at|date:"M d, Y" }}</td>
                                        <td class="text-end">
                                            <div class="btn-group btn-group-sm">
                                                <a href="{% url 'projects:task' current_project.id task.id %}"
                                                   class="btn btn-outline-primary">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                                <a href="{% url 'projects:edit_task' current_project.id task.id %}"
                                                   class="btn btn-outline-secondary">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="text-center py-5 bg-light rounded">
                        <div class="mb-3">
                            <i class="fas fa-tasks fs-1 text-muted"></i>
                        </div>
                        <p class="mb-1">Sem tarefas ainda</p>
                        <p class="text-muted">Comece adicionando sua primeira tarefa!</p>
                        <a href="{% url 'projects:add_task' current_project.id %}" class="btn btn-primary mt-2">
                            <i class="fas fa-plus-circle me-2"></i>Adicionar Primeira Tarefa
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}